[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
  "pip install -U yt-dlp --break-system-packages",
  "npm install"
]

[start]
cmd = "node index.js"
